version: '3'

services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/app"
    environment:
      DATABASE_URL: 'postgres://municipal_finance@postgres/municipal_finance'
      DJANGO_SECRET_KEY: "not-so-secret"
      SITE_ID: '3'
      PRELOAD_CUBES: 'true'
      DATA_PORTAL_URL: http://localhost:8002
    working_dir: /app
    ports:
      - '8002:8000'
    depends_on:
      - postgres
